# Generated by Django 2.2 on 2020-02-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderArticles', '0012_articlecomment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderarticle',
            name='category',
            field=models.CharField(choices=[('FOREX', 'Forex'), ('STOCKS', 'Stocks'), ('FUTURES', 'Futures')], default='STOCK MARKET', max_length=255),
        ),
    ]
