# Generated by Django 2.2 on 2019-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisarticle',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to=''),
        ),
    ]
