# Generated by Django 2.2 on 2019-12-24 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20191221_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisarticle',
            name='category',
            field=models.CharField(choices=[('COMMODITIES WEEKLY', 'COMMODITIES WEEKLY')], default='COMMODITIES WEEKLY', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysisarticle',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='analysis'),
            preserve_default=False,
        ),
    ]
