# Generated by Django 2.2 on 2020-01-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SliderArticles', '0006_articlecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
