# Generated by Django 2.2 on 2020-01-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SliderArticles', '0010_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='article_posts',
            new_name='article_post',
        ),
    ]
