# Generated by Django 2.2 on 2020-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderArticles', '0013_auto_20200220_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderarticle',
            name='image',
            field=models.ImageField(upload_to='slider'),
        ),
    ]
