# Generated by Django 2.2 on 2020-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SliderArticles', '0014_auto_20200324_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='articlecomment2',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='sliderarticle',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
