# Generated by Django 2.2 on 2020-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysiscomment_analysiscomment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisarticle',
            name='image',
            field=models.ImageField(upload_to='analysis'),
        ),
    ]
