# Generated by Django 2.2 on 2020-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200324_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisarticle',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='analysiscomment',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='analysiscomment2',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='analysispost',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
