version: '3.5'
services:
  app:
    image: ${CI_REGISTRY_IMAGE-localhost:5000/acaciax}/acaciax:${IMAGE_TAG-v1}
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 -w 3 AcaciaX.wsgi:application"
    expose:
      - "8000"
    networks:
      - traefik_net
    working_dir: /home/app
    volumes:
      - 'static:/home/app/static:ro'
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
  server:
    image: ${CI_REGISTRY_IMAGE-localhost:5000/acaciax}/nginx:${IMAGE_TAG-v1}
    build:
      context: nginx
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - traefik_net
    volumes:
      - 'static:/var/www/html/static'
  db:
    image: postgres:12.2-alpine
    volumes:
      - '/var/lib/pqsql/data:/var/lib/postgresql/data:rw'
      - "./docker/app/init.sh:/docker-entrypoint-initdb.d/init.sh"
    environment:
      - POSTGRES_PASSWORD
      - DB_NAME
      - DB_USER
      - DB_PASS
    networks:
      - traefik_net
networks:
  traefik_net:
volumes:
  static:
