version: '3.5'
services:
  app:
    image: ${CI_REGISTRY_IMAGE-localhost:5000/acaciax}/acaciax:${IMAGE_TAG-v1}
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && ls -l && python manage.py runserver 0.0.0.0:8000 --settings AcaciaX.settings"
    ports:
      - "8001:8000"
    networks:
      - traefik_net
    working_dir: /home/app
    volumes:
      - '.:/home/app'
  server:
    image: ${CI_REGISTRY_IMAGE-localhost:5000/acaciax}/nginx:${IMAGE_TAG-v1}
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
    networks:
      - traefik_net
    volumes:
      - './static:/var/www/html/static'
networks:
  traefik_net:
