version: '3.5'
services:
  app:
    image: ${CI_REGISTRY_IMAGE-localhost:5000/acaciax}/acaciax:${IMAGE_TAG-v1}
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "gunicorn --reload -b 0.0.0.0:8000 -w 3 AcaciaX.wsgi:application"
    command: bash -c "python manage.py migrate && ls -l && python manage.py runserver 0.0.0.0:8000 --settings AcaciaX.settings"
    ports:
      - "8001:8000"
    networks:
      - traefik_net
    working_dir: /home/app
    volumes:
      - '.:/home/app:rw'
    env_file:
      - .env
    environment:
      DB_ENGINE: django.db.backends.sqlite3
      DB_NAME: /home/app/db.sqlite3
  server:
    image: ${CI_REGISTRY_IMAGE-localhost:5000/acaciax}/nginx:${IMAGE_TAG-v1}
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
    networks:
      - traefik_net
    volumes:
      - './static:/var/www/html/static'
      - './media:/var/html/media'
networks:
  traefik_net:
