version: '3.5'
volumes:
  acme_data:
services:
  # This would normally not be here, but where you define your system services
  traefik:
    image: traefik:alpine
    command:
      - "--docker"
      - "--api"
      - "--docker.watch"
      - "--docker.domain=acaciax.co"
      - "--docker.exposedbydefault=false"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--insecureSkipVerify"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.acmelogging=true"
      - "--logLevel=DEBUG"
      - "--accessLog"
      - "--acme.storage=le/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnschallenge.provider=digitalocean"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=njugunasamuel12@gmail.com"
      - "--acme.domains=acaciax.co,www.acaciax.co,dash.acaciax.co"
      #- "--acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme_data:/le"
      # This may be needed (plus defining mailu_default external: true) if traefik lives elsewhere
    networks:
      - traefik_net
    environment:
      - DO_AUTH_TOKEN=$DO_AUTH_TOKEN
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:dash.acaciax.co"
      # get md5 from htpasswd or http://www.htaccesstools.com/htpasswd-generator/
      # and then double all $ to $$ to avoid docker-compose 
      - "traefik.frontend.auth.basic=acaciax_admin:$$apr1$$4MAfLt2B$$dVmbg0ovQUbLwAmVtj3w70"
      - "traefik.port=8080"

  server:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:acaciax.co,www.acaciax.co"
        - "traefik.port=80"
        - "traefik.frontend.redirect.regex=^https?://www.acaciax.co/(.*)"
        - "traefik.frontend.redirect.replacement=https://acaciax.co/$${1}"
