# Generated by Django 2.2 on 2019-12-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191224_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('STOCK_MARKET', 'STOCK_MARKET'), ('COMMODITIES', 'COMMODITIES'), ('FUTURES', 'FUTURES')], default='STOCK_MARKET', max_length=255),
        ),
    ]
