# Generated by Django 2.2 on 2019-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('STOCK MARKET', 'STOCK MARKET'), ('COMMODITIES', 'COMMODITIES'), ('FUTURES', 'FUTURES')], default='STOCK MARKET', max_length=255),
        ),
    ]
