# Generated by Django 2.2 on 2020-05-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200324_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('STOCKS', 'STOCKS'), ('COMMODITIES', 'COMMODITIES'), ('FUTURES', 'FUTURES')], default='STOCK MARKET', max_length=255),
        ),
    ]
