# Generated by Django 2.2 on 2019-12-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
