# Generated by Django 2.2 on 2020-01-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_comment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment2',
        ),
    ]
