# Generated by Django 2.2 on 2020-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_topic_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=10000),
        ),
    ]
