# Generated by Django 2.2 on 2019-12-24 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191221_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='news/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
